# Train Test Split

## Import the relevant libraries

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [9]:
a = np.arange(1,101)

In [10]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
b = np.arange(501,601)

In [12]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the data

In [20]:
train_test_split(a)

[array([ 46,  47,   1,  79,  68,  16,  77,   9,  70,  14,  92,  75,  19,
         96,  26,  20,  74,  76,  31,  55,  59,  94,  39,  54,  69,  66,
         83,  50,  33,  15,  95,  81,  17,  56, 100,  12,   5,  42,  24,
         99,  72,  23,  37,  53,  87,  18,  82,  58,  62,   8,  85,   3,
         44,  32,  11,  10,  43,  30,  78,  21,   4,   7,  67,  97,  71,
         86,   2,  73,  35,  91,  40,  45,  38,  98,  57]),
 array([36, 25, 48, 63, 64, 49, 65, 27, 28, 13, 80, 93, 51, 52, 90, 29, 88,
        22, 84, 41, 61, 60, 89, 34,  6])]

In [21]:
a_train, a_test = train_test_split(a)

## Explore the result

In [22]:
a_train.shape, a_test.shape

((75,), (25,))

In [23]:
a_train

array([ 28,  80,  92,  16, 100,  10,  72,  36,  71,   9,  59,  31,  24,
        30,  45,  98,  33,  78,  43,  19,  74,  99,  75,  52,  70,  13,
        53,  15,  84,  38,  37,  63,  17,  69,  44,  66,  54,  42,  57,
        89,  41,  76,  85,   3,  26,  67,  34,   5,  81,  55,  95,  73,
        94,  23,  65,   8,  93,  91,  87,  62,  39,  18,   7,  25,  64,
        90,   4,  35,  51,  47,  86,  50,  97,  68,  14])

In [24]:
a_test

array([83, 88, 22, 60, 46,  6, 20, 21, 29, 32, 96, 48, 82, 40, 61, 27, 79,
       12,  2, 56, 77, 58,  1, 11, 49])

Suppose we need a specified size of train and split, we could use below code.

In [25]:
a_train, a_test = train_test_split(a, test_size=0.2)

In [26]:
a_train

array([ 16,   7,  53,  51,  37,  85,  83,  44,  88,  27, 100,  67,  58,
        57,  19,  63,  64,  65,  87,  43,  11,  34,  81,  97,  10,  22,
        76,   9,  92,  36,  23,  46,  47,  70,  91,  94,  72,  74,  68,
        49,  77,  38,  45,  21,  79,  12,  40,  89,  66,  98,  75,  33,
        69,  41,   3,  20,  35,  42,  60,   5,   4,  62,  15,  82,  48,
        30,  25,  96,  73,  18,  78,  71,  17,  26,  54,  14,  86,   6,
        84,  29])

In [27]:
a_test

array([13, 55, 50, 32, 80, 56, 52, 59, 95,  8, 90, 31, 61,  2, 99, 24, 28,
       39,  1, 93])

If we want the results are not shuffled.

In [28]:
a_train, a_test = train_test_split(a, test_size=0.2, shuffle=False)  #by default, the shuffle is True

In [29]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [30]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

If we wanna get the exact same shuffled split in every split or we run the code, use argument 'random_state'. random_state=42 is the conventionally used number by the community.

In [34]:
a_train, a_test = train_test_split(a, test_size=0.2, random_state=42)

In [35]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [36]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

we add b in the argument.

In [37]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, random_state=42)

In [38]:
b_train.shape,b_test.shape

((80,), (20,))

In [39]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [40]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])